# Конфигурация callbacks
checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: val_loss
  dirpath: checkpoints
  filename: best-model-{epoch:02d}-{val_loss:.2f}
  save_top_k: 3
  mode: min
  save_last: true

early_stopping:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: val_loss
  patience: 10
  mode: min
  verbose: true

lr_monitor:
  _target_: pytorch_lightning.callbacks.LearningRateMonitor
  logging_interval: epoch

