# Основные параметры обучения
seed: 42
experiment_name: ai-image-classifier

# Данные
data:
  data_dir: data/processed       # путь к подготовленным данным (train/val/test)
  batch_size: 32
  num_workers: 4
  image_size: 224
  train_split: train
  val_split: val
  test_split: test

# Модель
model:
  backbone_name: efficientnet_b0
  num_classes: 2
  dropout: 0.3
  pretrained: true

# Тренинг
training:
  learning_rate: 1e-3
  weight_decay: 1e-5
  max_epochs: 20

# Lightning Trainer
lightning:
  accelerator: cpu
  devices: auto
  precision: 32
  log_every_n_steps: 50
  val_check_interval: 1.0
  enable_progress_bar: true
  enable_model_summary: true

# Callbacks (можно оставить пустыми или добавить Hydra instantiate конфиг)
callbacks: {}

# Logger (например, TensorBoard)
logger:
  _target_: pytorch_lightning.loggers.TensorBoardLogger
  save_dir: logs
  name: ai-image-classifier
